In [175]:
import sklearn.kernel_ridge as krr
import sklearn.preprocessing as pre
import pandas as pd
import numpy as np

In [2]:
train = pd.DataFrame.from_csv('data/other/train_df.csv')
val = pd.DataFrame.from_csv('data/other/val_df.csv')
test = pd.DataFrame.from_csv('data/other/test_df.csv')

In [124]:
train_examples = train.ix[:,0:26]
train_labels = train.ix[:,26]

val_examples = val.ix[:,0:26]
val_labels = val.ix[:,26]

test_examples = test.ix[:,0:26]
test_labels = test.ix[:,26]

X = pre.normalize(train_examples.values)
y = train_labels.values

X_val = pre.normalize(val_examples.values)
y_val = val_labels.values

X_test = pre.normalize(test_examples.values)
y_test = test_labels.values



array([[  6.95467813e-05,   6.95467813e-05,   6.95467813e-05, ...,
          5.05373277e-03,   9.59455803e-03,   1.34546942e-01],
       [  1.38383343e-04,   1.38383343e-04,   1.38383343e-04, ...,
          1.50491886e-03,   1.29446086e-02,   1.52146720e-01],
       [  8.65959679e-05,   8.65959679e-05,   8.65959679e-05, ...,
          1.93036845e-03,   1.30002197e-02,   1.42435935e-01],
       ..., 
       [  5.05185466e-04,   5.47689051e-04,   5.07614243e-04, ...,
          1.09537810e-03,   8.81645790e-03,   6.57226861e-02],
       [  1.89794202e-04,   2.05762464e-04,   1.90706674e-04, ...,
          5.57064232e-04,   1.33243742e-02,   2.48003992e-01],
       [  2.00118306e-02,   2.16955183e-02,   2.01080413e-02, ...,
          1.53456105e-02,   1.14298340e-01,   7.76276226e-01]])

In [73]:
# Normalize






array([ 0.146,  0.084,  0.122, ...,  0.653,  0.66 ,  0.506])

In [145]:
clf = krr.KernelRidge()

In [146]:
clf.fit(X, y)

KernelRidge(alpha=1, coef0=1, degree=3, gamma=None, kernel='linear',
      kernel_params=None)

In [147]:
math.sqrt(met.mean_squared_error(y, clf.predict(X)))

0.23400804131743755

In [148]:
math.sqrt(met.mean_squared_error(y_val, clf.predict(X_val)))

0.2070386693834345

In [149]:
clf.predict(X_val)

array([ 0.26687233,  0.26809746,  0.26691671, ...,  0.26012334,
        0.27752264,  0.24498193])

In [150]:
math.sqrt(met.mean_squared_error(y_test, clf.predict(X_test)))

0.26048690247546463

In [18]:
clf.score(val_examples.as_matrix(), val_labels.as_matrix())

-2.8146170752585116

In [20]:
k = clf.predict(val_examples.as_matrix())

2.0980579865388392e-07

In [24]:
import sklearn.metrics as met
import math
import sklearn.svm as svm

In [17]:
math.sqrt(met.mean_squared_error(val_labels.as_matrix(), clf.predict(val_examples.as_matrix())))

0.3900308396796226

In [167]:
clf2 = svm.SVR(kernel='poly')

In [168]:
ex = clf2.fit(X, y).predict(X_val)

In [169]:
math.sqrt(met.mean_squared_error(y, clf2.predict(X)))

0.239447126122699

In [170]:
math.sqrt(met.mean_squared_error(y_val, clf2.predict(X_val)))

0.2229353363958645

In [171]:
math.sqrt(met.mean_squared_error(y_test, clf2.predict(X_test)))

0.2697833225478837

In [43]:
math.sqrt(met.mean_squared_error(val_labels.as_matrix(), clf2.predict(val_examples.as_matrix())))

0.20725703898361297

In [51]:
math.sqrt(met.mean_squared_error(test_labels.as_matrix(), clf2.predict(test_examples.as_matrix())))

0.2478506070670278

In [52]:
clf2.predict(test_examples.as_matrix())

array([ 0.27956674,  0.27956674,  0.27956674, ...,  0.27956674,
        0.27956674,  0.27956674])

In [54]:
val_examples.as_matrix()

array([[  2.40000000e+01,   2.40000000e+01,   2.40000000e+01, ...,
          1.74400000e+03,   3.31100000e+03,   4.64310000e+04],
       [  2.40000000e+01,   2.40000000e+01,   2.40000000e+01, ...,
          2.61000000e+02,   2.24500000e+03,   2.63870000e+04],
       [  2.40000000e+01,   2.40000000e+01,   2.40000000e+01, ...,
          5.35000000e+02,   3.60300000e+03,   3.94760000e+04],
       ..., 
       [  3.78181818e+01,   4.10000000e+01,   3.80000000e+01, ...,
          8.20000000e+01,   6.60000000e+02,   4.92000000e+03],
       [  3.78181818e+01,   4.10000000e+01,   3.80000000e+01, ...,
          1.11000000e+02,   2.65500000e+03,   4.94170000e+04],
       [  3.78181818e+01,   4.10000000e+01,   3.80000000e+01, ...,
          2.90000000e+01,   2.16000000e+02,   1.46700000e+03]])

In [58]:
import sklearn.model_selection as gs
import scipy.stats

In [59]:
p_dict = {'C': scipy.stats.expon(scale=10000), 'gamma': scipy.stats.expon(scale=.1),
  'kernel': ['rbf'], 'epsilon': scipy.stats.expon(scale=0.001)}

In [65]:
searcher = gs.RandomizedSearchCV(svm.SVR(), param_distributions=p_dict, n_iter=1)

In [66]:
searcher.fit(train_examples.as_matrix(), train_labels.as_matrix())

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False),
          fit_params={}, iid=True, n_iter=1, n_jobs=1,
          param_distributions={'C': <scipy.stats._distn_infrastructure.rv_frozen object at 0x106c22908>, 'gamma': <scipy.stats._distn_infrastructure.rv_frozen object at 0x106c22cc0>, 'kernel': ['rbf'], 'epsilon': <scipy.stats._distn_infrastructure.rv_frozen object at 0x106c30f28>},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score=True, scoring=None, verbose=0)

In [69]:
searcher.predict(val_examples.as_matrix())

array([ 0.27983551,  0.27983551,  0.27983551, ...,  0.27983551,
        0.27983551,  0.27983551])

In [185]:
kr = gs.GridSearchCV(krr.KernelRidge(kernel='rbf', gamma=0.1), cv=5,
                  param_grid={"alpha": [1e0, 0.1, 1e-2],
                              "gamma": np.logspace(1, 5, 5)}, verbose=10)




In [186]:
kr.fit(X, y)

Fitting 5 folds for each of 15 candidates, totalling 75 fits
[CV] alpha=1.0, gamma=10.0 ...........................................
[CV] ............ alpha=1.0, gamma=10.0, score=0.118352, total=  12.3s
[CV] alpha=1.0, gamma=10.0 ...........................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   16.1s remaining:    0.0s


[CV] ........... alpha=1.0, gamma=10.0, score=-0.064461, total=  13.8s
[CV] alpha=1.0, gamma=10.0 ...........................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   34.4s remaining:    0.0s


[CV] ............ alpha=1.0, gamma=10.0, score=0.069878, total=  15.0s
[CV] alpha=1.0, gamma=10.0 ...........................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:   53.5s remaining:    0.0s


[CV] ............ alpha=1.0, gamma=10.0, score=0.084519, total=  13.6s
[CV] alpha=1.0, gamma=10.0 ...........................................


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:  1.2min remaining:    0.0s


[CV] ............ alpha=1.0, gamma=10.0, score=0.062493, total=  13.0s
[CV] alpha=1.0, gamma=100.0 ..........................................


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:  1.5min remaining:    0.0s


[CV] ........... alpha=1.0, gamma=100.0, score=0.150999, total=  12.6s
[CV] alpha=1.0, gamma=100.0 ..........................................


[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:  1.7min remaining:    0.0s


[CV] .......... alpha=1.0, gamma=100.0, score=-0.088722, total=  12.8s
[CV] alpha=1.0, gamma=100.0 ..........................................


[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:  2.0min remaining:    0.0s


[CV] ........... alpha=1.0, gamma=100.0, score=0.060110, total=  12.7s
[CV] alpha=1.0, gamma=100.0 ..........................................


[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:  2.3min remaining:    0.0s


[CV] ........... alpha=1.0, gamma=100.0, score=0.127000, total=  12.4s
[CV] alpha=1.0, gamma=100.0 ..........................................


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:  2.6min remaining:    0.0s


[CV] ........... alpha=1.0, gamma=100.0, score=0.081555, total=  12.4s
[CV] alpha=1.0, gamma=1000.0 .........................................
[CV] .......... alpha=1.0, gamma=1000.0, score=0.064873, total=  17.2s
[CV] alpha=1.0, gamma=1000.0 .........................................
[CV] ......... alpha=1.0, gamma=1000.0, score=-0.144168, total=  14.4s
[CV] alpha=1.0, gamma=1000.0 .........................................
[CV] ......... alpha=1.0, gamma=1000.0, score=-0.114146, total=  14.3s
[CV] alpha=1.0, gamma=1000.0 .........................................
[CV] .......... alpha=1.0, gamma=1000.0, score=0.026417, total=  13.7s
[CV] alpha=1.0, gamma=1000.0 .........................................
[CV] .......... alpha=1.0, gamma=1000.0, score=0.025133, total=  15.0s
[CV] alpha=1.0, gamma=10000.0 ........................................
[CV] ........ alpha=1.0, gamma=10000.0, score=-0.195577, total=  26.3s
[CV] alpha=1.0, gamma=10000.0 ........................................
[CV] .

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed: 28.5min finished


GridSearchCV(cv=5, error_score='raise',
       estimator=KernelRidge(alpha=1, coef0=1, degree=3, gamma=0.1, kernel='rbf',
      kernel_params=None),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'alpha': [1.0, 0.1, 0.01], 'gamma': array([  1.00000e+01,   1.00000e+02,   1.00000e+03,   1.00000e+04,
         1.00000e+05])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring=None, verbose=10)

In [187]:
kr.best_params_

{'alpha': 0.01, 'gamma': 10.0}

In [188]:
math.sqrt(met.mean_squared_error(y, kr.predict(X)))

0.20863364613006544

In [189]:
math.sqrt(met.mean_squared_error(y_val, kr.predict(X_val)))

0.1834304519023655

In [190]:
math.sqrt(met.mean_squared_error(y_test, kr.predict(X_test)))

0.2689755096776497

In [191]:
kr.best_params_

{'alpha': 0.01, 'gamma': 10.0}

In [194]:
svr = gs.GridSearchCV(svm.SVR(kernel='rbf', gamma=0.1), cv=5,
                   param_grid={"C": [1e0, 1e1, 1e2, 1e3],
                               "gamma": np.logspace(-2, 2, 5)}, verbose=10)

In [ ]:
svr.fit(X, y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV] C=1.0, gamma=0.01 ...............................................
[CV] ................ C=1.0, gamma=0.01, score=0.008107, total=   6.3s
[CV] C=1.0, gamma=0.01 ...............................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    9.9s remaining:    0.0s


[CV] ............... C=1.0, gamma=0.01, score=-0.060541, total=   5.9s
[CV] C=1.0, gamma=0.01 ...............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   19.4s remaining:    0.0s


[CV] ............... C=1.0, gamma=0.01, score=-0.063337, total=   6.1s
[CV] C=1.0, gamma=0.01 ...............................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:   29.2s remaining:    0.0s
